version: '3'
services:
  mongodb:
   image: mongo:latest
   container_name: "mongodb"
   restart: "always"
   volumes:
    - ./data/db:/data/db
   ports:
    - "27017:27017"
  node:
    build: .
    container_name: "node-dev"
    restart: "always"
    ports:
     - "1337:8888"
    volumes:
     - ./:/var/www
    links:
     - mongodb
    environment:
     - NODE_ENV=development
    command: npm run start-dev
