version: '3'
services:
  node-prod:
    build: .
    container_name: "node-prod"
    restart: "always"
    volumes:
    - ./:/var/www
#    tty: true
    ports:
     - "8888:8888"
    environment:
     - NODE_ENV=production
    command: npm start
